project_id = "fohjashmaedmmwvjtxwv"

[functions.blizzard-game-data]
verify_jwt = false

[functions.blizzard-character]
verify_jwt = false

[functions.simc-data-sync]
verify_jwt = false

[functions.fetch-patch-notes]
verify_jwt = false

[functions.blizzard-data-snapshot]
verify_jwt = false

[functions.blizzard-item-db]
verify_jwt = false
